# Generated by Django 4.2.16 on 2025-01-06 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='pending_friends',
            field=models.ManyToManyField(blank=True, help_text='The users that have sent a friend request to this user.', related_name='pending_friend_set', to=settings.AUTH_USER_MODEL, verbose_name='pending friends'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='friends',
            field=models.ManyToManyField(blank=True, help_text='The users that this user is friends with.', related_name='friend_set', to=settings.AUTH_USER_MODEL, verbose_name='friends'),
        ),
    ]
