# Generated by Django 4.2.16 on 2025-02-12 13:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_myuser_pending_friends_alter_myuser_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField()),
                ('participants', models.ManyToManyField(blank=True, help_text='Users participating in the tournament (maximum 10)', related_name='tournaments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
