# Generated by Django 4.2.16 on 2025-02-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tournament'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
