# Generated by Django 4.2.16 on 2024-12-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_myuser_ligue_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchhistory',
            name='type',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
