# Generated by Django 4.2.16 on 2025-02-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='pseudo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
