services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certificates:/etc/ssl/certs
      - ./spa:/app/spa
      - ./media:/app/media
    depends_on:
      - django
    networks:
      - trans_network

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./init_redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6378:6378"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - trans_network

  django:
    container_name: django
    build:
      context: ./init_django/
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
    depends_on:
      - db_postgre
      - redis
    networks:
      - trans_network
    command: ./init_django/script.sh db_postgre

  db_postgre:
    container_name: db_postgre
    image: postgres:14.1-alpine
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db_postgre:/var/lib/postgresql/data
      # - db_postgre:/root/42/ft_transcendance/Backend/dbVolumes/
      - ./init_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - trans_network

volumes:
  db_postgre:
    driver: local
  media_volume:

networks:
  trans_network:
    driver: bridge