# Generated by Django 4.2.16 on 2025-02-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_myuser_pseudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='pseudo',
            field=models.CharField(default='temp_pseudo', max_length=100),
        ),
    ]
