# Generated by Django 4.2.16 on 2025-02-21 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_tournamentmatch_tournament_all_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='finalist',
            field=models.ManyToManyField(blank=True, related_name='finalist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.ManyToManyField(blank=True, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
