# Generated by Django 4.2.16 on 2025-03-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_refreshtoken_accesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_oauth',
            field=models.BooleanField(default=False),
        ),
    ]
