# Generated by Django 4.2.16 on 2025-03-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_pendingmatch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingMatch',
        ),
    ]
