# Generated by Django 4.2.16 on 2025-03-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_delete_pendingmatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
