# Generated by Django 4.2.16 on 2025-03-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_delete_pendingmatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='pseudo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
